[mgr]
layout         = [ 1, 4, 3 ]
sort_by        = "mtime"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 0

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 5
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
folder = [
	{ run = 'nvim "$1"', block = true,desc = "neovim", for = "linux" },
	{ run = 'code  "$@"',orphan = true, desc = "vscode" , for = "linux" },
	{ run = '''fish -c "lazygit -p "$1""''', block = true,desc = "lazygit", for = "linux" },
	{ run = 'basename "$@" | xargs -I {} tar --use-compress-program=pigz -cf ~/Downloads/{}.tar.gz {}',orphan = true, desc = "archive" , for = "linux"  },

]
archive = [
	# { run = 'basename "$@" | xargs tar xf ', orphan = true, desc = "tar xf" , for = "linux" },
	# { run = 'basename "$@" | xargs tar xzf ', orphan = true, desc = "tar xzf" , for = "linux" },
	# { run = 'unzip "$1"', orphan = true, desc = "unzip" , for = "linux" },
	# { run = 'unar "$1"', orphan = true, desc = "unrar" , for = "linux" },
	#{ run = 'ouch decompress "$1" ', orphan = true, desc = "ouch decompress" , for = "linux" },
	{ run = '7z x "$1" ', orphan = true, desc = "eksuturacku here" , for = "linux" },
]

text = [
	{ run = 'nvim "$1"', block = true,desc = "neovim", for = "linux" },
	{ run = 'code  "$@"',orphan = true, desc = "vscode" , for = "linux" },
	{ run = 'zathura "$@"',orphan = true, desc = "zathura"  , for = "linux" },
]
image = [
	{ run = 'imv-dir "$@"',  orphan = true, desc = "imv" , for = "linux"},
	{ run = 'sxiv -a "$@"',  orphan = true, desc = "sxiv" , for = "linux"},
]
video = [
	{ run = 'mpv "$@" ', orphan = true, desc = "mpv" , for = "linux" },
	{ run = 'ffmpeg -i "$@" -vf "fps=10" -loop 0 "$@".gif', orphan = true, desc = "change to gif"  , for = "linux" },	

	{ run = 'wine "$1"', orphan = true, desc = "wine gamij", for = "linux" },
	{ run = 'umu-run "$1"', orphan = true, desc = "umu-run", for = "linux" },
	{ run = 'LC_ALL=ja_JP.UTF-8 wine "$1"', orphan = true, desc = "wine japon", for = "linux" },

]
audio = [
	{ run = 'mpv "$@" ' , orphan = true, desc = "mpv" , for = "linux"},
]

document = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "xdg-open" , for = "linux" },
	{ run = 'libreoffice "$@" ' , orphan = true, desc = "libreoffice" , for = "linux"},
]

executable = [
	{ run = 'wine "$1"', orphan = true, desc = "wine", for = "linux" },
]

fallback = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "xdg-open" , for = "linux" },
	{ run = 'nvim "$1"', block = true,desc = "neovim", for = "linux" },
]
winej = [
	{ run = 'wine "$1"', orphan = true, desc = "wine", for = "linux" },
	{ run = 'LC_ALL=ja_JP.UTF-8 wine "$1"', orphan = true, desc = "wine japon", for = "linux" },
	{ run = 'umu-run "$1"', orphan = true, desc = "umu-run", for = "linux" },
]
[open]
rules = [
	{ name = "*/", use = ["folder"] },
	{ name = "*.sh", use = ["executable"] },
	{ name = "*.gif", use = ["image"] },

  { name = "*.exe", use = ["winej"]},

	{ mime = "text/*", use = ["text"] },
	{ mime = "image/*", use = ["image"] },
	{ mime = "video/*", use = ["video"] },
	{ mime = "application/octet-stream",use = ["video"]},
	{ mime = "audio/*", use = ["audio"] },
	{ mime = "inode/empty", use = ["text"] },
	{ mime = "application/json", use = ["text"] },

	{ mime = "application/zip", use = ["archive"] },
	{ mime = "application/gzip", use = ["archive"] },
	{ mime = "application/x-bzip", use = ["archive"] },
	{ mime = "application/x-bzip2", use = ["archive"] },
	{ mime = "application/x-tar", use = ["archive"] },
	{ mime = "application/x-7z-compressed", use = ["archive"] },
	{ mime = "application/x-rar", use = ["archive"] },
	{ mime = "application/pdf", use = ["document"] },
	{ mime = "application/epub+zip", use = ["document"] },
	{ mime = "application/x-mobipocket-ebook", use = ["document"] },

	{ mime = "*", use = ["fallback"] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false

[[plugin.prepend_fetchers]]
id   = "mime"
if   = "!(mime|dummy)"
name = "*"
run  = "mime-ext"
prio = "high"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"


[[plugin.prepend_fetchers]]
id   = "current-size"
name = "*"
run  = "current-size"

[[plugin.prepend_fetchers]]
id   = "current-size"
name = "*/"
run  = "current-size"


[[plugin.prepend_previewers]]
name = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
name = "*.html"
run  = 'piper -- w3m -I UTF-8 -T text/html "$1"'

[[plugin.prepend_previewers]]
mime = "text/html"
run  = 'piper -- w3m -I UTF-8 -T text/html "$1"'

[[plugin.prepend_previewers]]
mime = "application/epub+zip"
run  = "epub-preview"

[[plugin.prepend_previewers]]
mime = "application/octet-stream"
run  = "video"

[[plugin.prepend_previewers]]
name = "*.csv"
run  = 'piper -- bat -p --color=always "$1"'

